# Generated by Django 3.2.2 on 2021-05-25 11:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0003_alter_block_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
