# Generated by Django 3.2.2 on 2021-05-26 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0004_alter_block_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.DateField()),
                ('To', models.DateField()),
                ('property_type', models.CharField(choices=[('Flat', 'Flat'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Shop', 'Shop')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='collection_water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Flat', 'Flat'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Shop', 'Shop')], max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('water_bill_generated', models.CharField(max_length=100)),
                ('water_bill_received', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.block')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.floor')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.society')),
            ],
        ),
        migrations.CreateModel(
            name='collection_rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Flat', 'Flat'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Shop', 'Shop')], max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('rent_generated', models.CharField(max_length=100)),
                ('rent_received', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.block')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.floor')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.society')),
            ],
        ),
        migrations.CreateModel(
            name='collection_electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Flat', 'Flat'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Shop', 'Shop')], max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('electricity_generated', models.CharField(max_length=100)),
                ('electricity_received', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.block')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.floor')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.society')),
            ],
        ),
        migrations.CreateModel(
            name='collection_DG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Flat', 'Flat'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Shop', 'Shop')], max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('bill_generated', models.CharField(max_length=100)),
                ('bil_received', models.CharField(max_length=100)),
                ('DG_used', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.block')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.floor')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.society')),
            ],
        ),
        migrations.CreateModel(
            name='collection_CAM_received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Flat', 'Flat'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Shop', 'Shop')], max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('CAM_demand', models.CharField(max_length=100)),
                ('CAM_received', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.block')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.floor')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.society')),
            ],
        ),
    ]
