# Generated by Django 3.2.2 on 2021-05-26 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0006_rename_bil_received_collection_dg_bill_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_for', models.CharField(max_length=100)),
                ('type_of_unit', models.CharField(max_length=100)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.society')),
            ],
        ),
        migrations.CreateModel(
            name='electricity_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Flat', 'Flat'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Shop', 'Shop')], max_length=100)),
                ('property_number', models.PositiveIntegerField()),
                ('client_name', models.CharField(max_length=100)),
                ('consumption_unit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('per_unit_charge', models.DecimalField(decimal_places=2, max_digits=7)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.block')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.floor')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.society')),
            ],
        ),
        migrations.CreateModel(
            name='discount_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Flat', 'Flat'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Shop', 'Shop')], max_length=100)),
                ('property_number', models.CharField(max_length=50)),
                ('cam', models.CharField(max_length=100)),
                ('dis_per', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dis_cam', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valid_period', models.CharField(max_length=3)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.block')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.floor')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.society')),
            ],
        ),
        migrations.CreateModel(
            name='discount_society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=3)),
                ('dis_per', models.DecimalField(decimal_places=2, max_digits=4)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.block')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.society')),
            ],
        ),
    ]
