# Generated by Django 3.2.2 on 2021-05-26 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0007_discount_society_discount_user_electricity_bill_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection_Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='year')),
                ('amount', models.IntegerField()),
                ('ROI', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('income_from_fund', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='water_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Flat', 'Flat'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Shop', 'Shop')], max_length=100)),
                ('property_number', models.PositiveIntegerField()),
                ('client_name', models.CharField(max_length=100)),
                ('consumption_unit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('per_unit_charge', models.DecimalField(decimal_places=2, max_digits=7)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.block')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.floor')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.society')),
            ],
        ),
    ]
