# Generated by Django 3.2.2 on 2021-05-27 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0008_collection_income_water_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAM_calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Flat', 'Flat'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Shop', 'Shop')], max_length=100)),
                ('property_number', models.PositiveIntegerField()),
                ('client_name', models.CharField(max_length=150)),
                ('CAM', models.DecimalField(decimal_places=2, max_digits=10)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.block')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.floor')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.society')),
            ],
        ),
        migrations.CreateModel(
            name='assigned_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ID', models.IntegerField()),
                ('date', models.DateField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('type_of_property', models.CharField(choices=[('Flat', 'Flat'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Shop', 'Shop')], max_length=100)),
                ('property_number', models.IntegerField()),
                ('rent', models.BooleanField(default=False)),
                ('CAM', models.CharField(max_length=10)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.block')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.floor')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_app.society')),
            ],
        ),
    ]
