# Generated by Django 3.2.2 on 2021-05-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0009_assigned_property_cam_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial_shop',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS_app.block'),
        ),
        migrations.AddField(
            model_name='commercial_shop',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS_app.floor'),
        ),
    ]
