# Generated by Django 3.2.2 on 2021-05-29 12:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0010_auto_20210527_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
