# Generated by Django 3.2.2 on 2021-06-01 05:57

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0011_alter_block_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
