# Generated by Django 3.2.2 on 2021-06-01 15:32

import CMS_app.validators
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0012_alter_block_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='permanent_address',
        ),
        migrations.AddField(
            model_name='client',
            name='current_address',
            field=models.CharField(default='jaipur', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email_address',
            field=models.EmailField(default='cli@crm.in', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='cli', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='user', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='mobile_number',
            field=models.CharField(default=9876567, max_length=10, validators=[CMS_app.validators.only_digit]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='permanent_address',
            field=models.CharField(default='jaipur', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='block',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.CharField(max_length=10, validators=[CMS_app.validators.only_digit]),
        ),
    ]
