# Generated by Django 3.2.2 on 2021-06-01 11:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0012_alter_block_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
