# Generated by Django 3.2.2 on 2021-06-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0013_alter_block_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block',
            field=models.CharField(max_length=100),
        ),
    ]
