
# Generated by Django 3.2.2 on 2021-06-02 02:26

# Generated by Django 3.2.2 on 2021-06-02 03:59


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0013_auto_20210601_2102'),
        ('CMS_app', '0014_alter_block_block'),
    ]

    operations = [
    ]
